name: "blog"
mode: "dev"
port: 8080
version: "v0.1.4"
start_time: "2022-07-01"
machine_id: 1
email_secret_code: ""
access_key: ""
secret_key: ""
bucket: "blogoss0"
img_url: "image.fishworm.top/"

auth:
  jwt_expire: 8760
log:
  level: "info"
  filename: "blog.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "blog"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100