basePath: /api/v1
definitions:
  controller._ResponsePostList:
    properties:
      code:
        description: 业务响应状态码
        type: integer
      data:
        description: 数据
        items:
          $ref: '#/definitions/models.ApiPostDetail'
        type: array
      message:
        description: 提示信息
        type: string
    type: object
  models.ApiPostDetail:
    properties:
      author_name:
        type: string
      community_id:
        description: 社区ID
        type: integer
      content:
        description: 文章内容
        type: string
      create_time:
        type: string
      id:
        type: integer
      introduction:
        type: string
      name:
        type: string
      title:
        description: 文章标题
        type: string
      vote_num:
        type: integer
    required:
    - community_id
    - content
    - title
    type: object
  models.ParamLogin:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  models.ParamPost:
    properties:
      content:
        description: 文章内容
        type: string
      title:
        description: 文章标题
        type: string
    required:
    - content
    - title
    type: object
  models.ParamSignUp:
    properties:
      password:
        description: 密码
        maxLength: 24
        minLength: 6
        type: string
      re_password:
        description: 重复密码
        type: string
      username:
        description: 用户名
        maxLength: 24
        minLength: 6
        type: string
    required:
    - password
    - re_password
    - username
    type: object
  models.ParamVoteData:
    properties:
      direction:
        description: 增长票1 还是返回票-1 取消票0
        enum:
        - 1
        - 0
        - -1
        example: "0"
        type: string
      post_id:
        description: UserID 从请求中获取当前的用户
        type: string
    required:
    - post_id
    type: object
  models.Post:
    properties:
      community_id:
        description: 社区ID
        type: integer
      content:
        description: 文章内容
        type: string
      title:
        description: 文章标题
        type: string
    required:
    - community_id
    - content
    - title
    type: object
host: localhost:8080
info:
  contact:
    name: zhou
    url: https://www.fishworm96.github.io
  description: Go web blog
  title: blog项目接口文档
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 登录接口
      parameters:
      - description: 登录参数
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/models.ParamLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 登录接口
      tags:
      - 用户相关接口
  /post:
    get:
      consumes:
      - application/json
      description: 获取帖子列表接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: 获取帖子列表接口
      tags:
      - 帖子相关接口
  /post/{id}:
    get:
      consumes:
      - application/json
      description: 根据帖子id获取帖子信息的接口
      parameters:
      - description: 查询帖子id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: 帖子信息接口
      tags:
      - 帖子相关接口
  /post/delete/{id}:
    delete:
      consumes:
      - application/json
      description: 根据帖子id删除帖子的接口
      parameters:
      - description: 删除文章帖子参数
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: 删除帖子接口
      tags:
      - 帖子相关接口
  /post/edit/{id}:
    put:
      description: 根据文章id来接收标题和内容修改帖子接口
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章id
        in: path
        name: id
        required: true
        type: integer
      - description: 修改帖子内容
        in: body
        name: ParamPost
        schema:
          $ref: '#/definitions/models.ParamPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: 更新帖子接口
      tags:
      - 帖子相关接口
  /posts:
    post:
      consumes:
      - application/json
      description: 创建帖子接口
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: 社区ID
        in: body
        name: PostParam
        schema:
          $ref: '#/definitions/models.Post'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: 创建帖子接口
      tags:
      - 帖子相关接口
  /posts2:
    get:
      consumes:
      - application/json
      description: 可按社区时间或分数排序查询帖子列表接口
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      - description: 可以为空
        in: query
        name: community_id
        type: integer
      - description: 排序依据
        example: score
        in: query
        name: order
        type: string
      - description: 页码
        example: 1
        in: query
        name: page
        type: integer
      - description: 每页数据量
        example: 1
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller._ResponsePostList'
      security:
      - ApiKeyAuth: []
      summary: 升级版帖子列表接口
      tags:
      - 帖子相关接口
  /signUp:
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - description: 注册参数
        in: body
        name: SignUp
        required: true
        schema:
          $ref: '#/definitions/models.ParamSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: 注册用户接口
      tags:
      - 用户相关接口
  /vote:
    post:
      consumes:
      - application/json
      description: 根据帖子id和投票方向来投票的接口
      parameters:
      - description: 投票参数
        in: body
        name: ParamVoteData
        required: true
        schema:
          $ref: '#/definitions/models.ParamVoteData'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 投票接口
      tags:
      - 投票相关接口
swagger: "2.0"
